//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Biblioteca.GUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlibliotecaContext : DbContext
    {
        public BlibliotecaContext()
            : base("name=BlibliotecaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Ejemplares> Ejemplares { get; set; }
        public virtual DbSet<Estante> Estante { get; set; }
        public virtual DbSet<Estanterias> Estanterias { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<Publicacion> Publicacion { get; set; }
        public virtual DbSet<Revista> Revista { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
