//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Biblioteca.GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int LibroID { get; set; }
        public string ISBM { get; set; }
        public string Titulo { get; set; }
        public string Formato { get; set; }
        public string NumeroPaginas { get; set; }
        public int PublicacionID { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> AutorID { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Publicacion Publicacion { get; set; }
    }
}
