//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Biblioteca.GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publicacion()
        {
            this.Libro = new HashSet<Libro>();
            this.Revista = new HashSet<Revista>();
        }
    
        public int PublicacionID { get; set; }
        public string Tematica { get; set; }
        public string Idioma { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public string Editorial { get; set; }
        public int EjemplarID { get; set; }
        public string TipoPublicacion { get; set; }
    
        public virtual Ejemplares Ejemplares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Libro> Libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revista> Revista { get; set; }
    }
}
