//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Biblioteca.GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revista
    {
        public int RevistaID { get; set; }
        public string Numero { get; set; }
        public string NombreRevista { get; set; }
        public int PublicacionID { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
    }
}
